# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: ALICE CAST
description: >- # this means to ignore newlines until "baseurl:"
  Bem vindo ao sensacional site de cursos do Alice.
baseurl: /alice_cast # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

# collections
collections:
  aulas:
    output: true
    permalink: /:collection/:path
  software:
    output: true
    permalink: /:collection/:path
  autores:
    output: true
    permalink: /:collection/:path
  cursos:
    output: true
    permalink: /:collection/:path

# collection default setup
defaults:
  -
    scope:
      path: "_aulas"
      type: aulas
    values:
      layout: "aula"
      author: "ALICE"
  -
    scope:
      path: "_autores"
      type: autores
    values:
      layout: "author"
  -
    scope:
      path: "_software"
      type: software
    values:
      layout: "software"
  -
    scope:
      path: "_cursos"
      type: cursos
    values:
      layout: "curso"

# config lang
default_lang: pt
languages:
  - en
  - pt


exclude:
  - makefile
  - Gemfile
  - Gemfile.lock
  - makefile
  - script
  - _aulas/*.mkv
